version: '3.8'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/Crease.WebUI/Dockerfile
    environment:
      - "UseInMemoryDatabase=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=crease123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: on-failure